### ISSUE TITLE
Unable to complete npm install

### ISSUE THREAD

**Issue by loganblankk** [pluralsight-projects/Angular-AlbumStoreProductPage#34]
I am unable to run npm install when initially setting up the project. It would first run for maybe a second then quit. Allowing me to run a new command. I looked online and some recommended removing the package-lock.json file. I deleted that file and now it will run longer but quits during the fetchMetaData stage. No errors are returned during this. I created a test angular project on my desktop and ran npm install to see what happens and it worked without any issues. 

Here are the current versions I am running:
NPM: 5.5.1
CLI: 1.5.3
Node: 8.9.1

**Comment by loganblankk** [comment]
when running npm install -verbose I receive this message 

```
820 silly fetchPackageMetaData error for nightmare@git+https://github.com/bokuweb/nightmare.git#master Error while executing:
820 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/bokuweb/nightmare.git
820 silly fetchPackageMetaData
820 silly fetchPackageMetaData fatal: unable to access 'https://github.com/bokuweb/nightmare.git/': SSL certificate problem: self signed certificate in certificate chain
820 silly fetchPackageMetaData
820 silly fetchPackageMetaData exited with error code: 128
821 verbose stack Error: exited with error code: 128
821 verbose stack     at ChildProcess.onexit (C:\Users\logan.blankenship\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
821 verbose stack     at emitTwo (events.js:126:13)
821 verbose stack     at ChildProcess.emit (events.js:214:7)
821 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
822 verbose cwd C:\Users\logan.blankenship\Desktop\dev-tuts\Angular-AlbumStoreProductPage-master
823 verbose Windows_NT 10.0.14393
824 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\logan.blankenship\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-verbose"
825 verbose node v8.9.1
826 verbose npm  v5.5.1
827 error Error while executing:
827 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/bokuweb/nightmare.git
827 error
827 error fatal: unable to access 'https://github.com/bokuweb/nightmare.git/': SSL certificate problem: self signed certificate in certificate chain
827 error
827 error exited with error code: 128
828 verbose exit [ 1, true ]
```

**Comment by SRM19** [comment]
Installing git solved the issue
