### ISSUE TITLE
Project will not build or run

### ISSUE THREAD

**Issue by TomHomer** [pluralsight-projects/Angular-AlbumStoreProductPage#65]
Following the instructions at https://app.pluralsight.com/projects/build-an-album-store-product-page-with-angular/setup/ does not produce a working project for me.

ng test fails as it cannot find karma:

```
C:\Users\tomh\Documents\GitHub\Angular-AlbumStoreProductPage>ng test
Cannot find module 'karma' from 'C:\Users\tomh\Documents\GitHub\Angular-AlbumStoreProductPage'
Error: Cannot find module 'karma' from 'C:\Users\tomh\Documents\GitHub\Angular-AlbumStoreProductPage'
    at Function.module.exports [as sync] (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\resolve\lib\sync.js:58:15)
    at Object.requireProjectModule (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\utilities\require-project-module.js:6:28)
    at Promise (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\tasks\test.js:24:52)
    at new Promise (<anonymous>)
    at Class.run (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\tasks\test.js:23:16)
    at Class.run (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\commands\test.js:122:25)
    at resolve (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:240:12)
    at Promise.resolve.then.then (C:\Users\tomh\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:140:24)
```

ng build or ng serve fail with a dependency error:

```
C:\Users\tomh\Documents\GitHub\Angular-AlbumStoreProductPage>ng serve
You seem to not be depending on "@angular/core". This is an error.
```

I have followed advice online to resolve this (delete package-lock.json and retry, try npm link and npm update) but the best I can get to is:

```
C:\Users\tomh\Documents\GitHub\Angular-AlbumStoreProductPage>ng build
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.
```

Following these instructions gets me back to "You seem to not be depending on "@angular/core". This is an error."

**Comment by TomHomer** [comment]
Never worked out what this was but I have been able to resolve it by:

- Using YARN not NPM
- Installing Git for windows (as GitHubDesktop doesn't share nicely?)
